### ISSUE TITLE
Problem retrieving a data set from wave to a dataframe Spark 2.0

### ISSUE THREAD

**Issue by malsmith** [springml/spark-salesforce#4] opened 2016-10-03 23:20 UTC
After running Spark 2.0 
`
bin/spark-shell  --packages com.springml:spark-salesforce_2.10:1.0.6
`

With this code 

`
val sqlContext = new SQLContext(sc)
// Reading Dataset
val saql = "q = load \"0FbB00000000AN5KAM/0FcB00000000VDsKAM\"; q = foreach q generate 'Att' as 'Att', 'Column2' as 'Column2', 'FantPos' as 'FantPos', 'G' as 'G', 'TD1' as 'TD1', 'TD2' as 'TD2', 'Tgt' as 'Tgt', 'Tm' as 'Tm';"

var sfWaveDF3 = sqlContext.
                read.
                format("com.springml.spark.salesforce").
                option("username", "msmiXXXX@rpas.com").
                option("password", "coSFSFSFSDFJvqBezm7mCgOQ0m").
                option("saql", saql).
                option("login","https://login.salesforce.com").
                option("inferSchema", "true").
                option("resultVariable","q").
                load()
`

I get this error

`
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpPost.setConfig(Lorg/apache/http/client/config/RequestConfig;)V
  at com.springml.salesforce.wave.util.HTTPHelper.post(HTTPHelper.java:50)
  at com.springml.salesforce.wave.util.HTTPHelper.post(HTTPHelper.java:28)
  at com.springml.salesforce.wave.impl.WaveAPIImpl.query(WaveAPIImpl.java:56)
  at com.springml.salesforce.wave.impl.WaveAPIImpl.queryWithPagination(WaveAPIImpl.java:72)
  at com.springml.salesforce.wave.impl.WaveAPIImpl.queryWithPagination(WaveAPIImpl.java:29)
  at com.springml.spark.salesforce.DatasetRelation.queryWave(DatasetRelation.scala:69)
  at com.springml.spark.salesforce.DatasetRelation.read(DatasetRelation.scala:54)
  at com.springml.spark.salesforce.DatasetRelation.<init>(DatasetRelation.scala:48)
  at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:79)
  at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:53)
  at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:39)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:315)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
`

**Comment by samuel-pt** [comment] 2016-10-04 11:50
It seems, Apache HTTP library is changed in Spark 2.0. Will update the library, run against Spark 2.0 and update this ticket. 

Thanks for creating the issue

**Comment by malsmith** [comment] 2016-10-07 16:15
Thanks - I did try downgrading to 
`
docker run --rm -it -p 4040:4040 gettyimages/spark:1.6.2-hadoop-2.6 bin/spark-shell --packages com.springml:spark-
salesforce_2.10:1.0.6
`
Same error so maybe the new library was introduced after Spark 1.4 or 1.5

**Comment by samuel-pt** [comment] 2016-10-10 06:26
No. We've been using Spark Salesforce connector with Spark 1.6.2 without any issues. Do you have any additional packages along with Spark Salesforce connector? Or is it a custom build Spark image?

**Comment by nickhakobian** [comment] 2016-11-15 19:23
This error also exists on Spark 1.6 with the CDH 5.7.0 distribution. It appears an interval version of this library is included which does not contain the needed function.

**Comment by springml** [comment] 2017-03-13 07:46
@malsmith Sorry for late reply. Could please test this with latest release and let us know for any issues

**Comment by leletan** [comment] 2017-07-25 01:13
This still seems not fixed. I am getting the same issue after moving to `com.springml:spark-salesforce_2.11:1.1.0` on spark 2.0+ cluster

**Comment by springml** [comment] 2017-07-25 04:47
@leletan - Are you getting this issue in Spark 2.0 from CDH distribution or with vanilla Apache Spark?

**Comment by leletan** [comment] 2017-07-25 05:05
I am getting this when deploying the big jar onto a docker-compose local cluster using https://github.com/gettyimages/docker-spark/blob/master/docker-compose.yml

**Comment by samuel-pt** [comment] 2017-07-25 05:16
Please provide me the simple steps to start docker-compose with fat jar. Do we need to update the compose files to include spark-salesforce connector?

**Comment by leletan** [comment] 2017-07-26 23:02
sure.
1. `docker-compose up` of the previous mentioned docker-compose.yml.
2. sbt assembly the job jar, and copy it into the running docker instances (spark master and spark worker)
3. docker exec -it spark_master bin/spark-submit \
        --master spark://master:6066 \
        --deploy-mode cluster \
        --class <class for the main> \
        --executor-memory 512M \
        --driver-memory 512M \
        --total-executor-cores 2 \
       <jar path in docker>

**Comment by leletan** [comment] 2017-07-26 23:03
the build.sbt looks like:
...
libraryDependencies ++= {
  val sparkVersion = "2.1.0"

  Seq(
    // Apache Spark dependencies
    "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",

    // Salesforce integration
    "com.springml" % "spark-salesforce_2.11" % "1.1.0",

...

**Comment by leletan** [comment] 2017-07-26 23:08
The job itself is very similar to the demo in readme

**Comment by springml** [comment] 2017-07-28 13:36
@leletan I am able to reproduce this issue. Hadoop 2.7.3 contains very old httpclient jar

```
hadoop-2.7.3/share/hadoop/common/lib/httpclient-4.2.5.jar
hadoop-2.7.3/share/hadoop/tools/lib/httpclient-4.2.5.jar

```
But we are shipping he connector with httpclient-4.5.jar. 
In the docker container SPARK_DIST_CLASSPATH has the below paths 
```
# echo $SPARK_DIST_CLASSPATH
/usr/hadoop-2.7.3/etc/hadoop/*:/usr/hadoop-2.7.3/share/hadoop/common/lib/*:/usr/hadoop-2.7.3/share/hadoop/common/*:/usr/hadoop-2.7.3/share/hadoop/hdfs/*:/usr/hadoop-2.7.3/share/hadoop/hdfs/lib/*:/usr/hadoop-2.7.3/share/hadoop/hdfs/*:/usr/hadoop-2.7.3/share/hadoop/yarn/lib/*:/usr/hadoop-2.7.3/share/hadoop/yarn/*:/usr/hadoop-2.7.3/share/hadoop/mapreduce/lib/*:/usr/hadoop-2.7.3/share/hadoop/mapreduce/*:/usr/hadoop-2.7.3/share/hadoop/tools/lib/*
```

This overwrites the httpclient present in spark-salesforce assembly jar. 

I don't think reverting the httpclient to old version is right solution for this. 

I've verified this vanilla Apache spark and spark comes along with HDP and this connector is working fine.

Could you please try using this in any other spark apart from this docker image?

**Comment by leletan** [comment] 2017-07-28 16:52
Sure. Thanks for the advices!

**Comment by samuel-pt** [comment] 2017-08-02 06:22
@leletan Please reopen this issue if you face this issue in other spark platforms

**Closed by samuel-pt** 2017-08-02 06:23 UTC

**Comment by luisvillarreal** [comment] 2020-03-25 20:27
I know this is closed, but noticed that this issue still happens in spark 2.4.0. Works fine with 2.4.4, only thing is that I can go as far as 2.4.0 because of CDH. Was wondering if there is a workaround. Thanks
