### ISSUE TITLE
Writing an empty dataset results in an empty batch being written to salesforce

### ISSUE THREAD

**Issue by nojo** [springml/spark-salesforce#11] opened 2017-03-03 16:58 UTC
When an empty dataset is written, no batch should be created.  As it is, an batch is created and then submitted, and salesforce responds with an error response.

**Comment by springml** [comment] 2017-03-13 12:43
@nojo We are getting the below exception and I think you got the same as well

`Caused by: java.lang.Exception: Batch '75115000007k73CAAQ' failed with error 'InvalidBatch : Records not found'
	at com.springml.salesforce.wave.impl.BulkAPIImpl.isCompleted(BulkAPIImpl.java:93)
	at com.springml.spark.salesforce.SFObjectWriter.writeData(SFObjectWriter.scala:44)
	at com.springml.spark.salesforce.DefaultSource.updateSalesforceObject(DefaultSource.scala:154)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:130)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:426)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
	... 36 more
Error: Error in save : java.lang.Exception: Batch '75115000007k73CAAQ' failed with error 'InvalidBatch : Records not found'
	at com.springml.salesforce.wave.impl.BulkAPIImpl.isCompleted(BulkAPIImpl.java:93)
	at com.springml.spark.salesforce.SFObjectWriter.writeData(SFObjectWriter.scala:44)
	at com.springml.spark.salesforce.DefaultSource.updateSalesforceObject(DefaultSource.scala:154)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:130)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:426)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

**Comment by springml** [comment] 2017-03-13 13:18
This issue is resolved by commits in [spark-salesforce](https://github.com/springml/spark-salesforce/commit/1fb828f485f5f2cfd7f58bfa5d746061023759f8) and [salesforce-wave-api](https://github.com/springml/salesforce-wave-api/commit/0ac76aeb2221d9e7038229fd352a8694e8cde7e9)

**Closed by springml** 2017-03-13 13:18 UTC
Labels: bug
